#!/usr/bin/env bash
# Copyright (C) 2025-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
# =============================================================================
# generate-vault-secrets.sh — Generate docker/vault.yml with all credentials
# =============================================================================
# Run once before deploying (deploy.sh calls this automatically if vault.yml
# does not yet exist).
#
# Usage:
#   bash docker/scripts/generate-vault-secrets.sh          # write to docker/vault.yml
#   VAULT_DIR=/custom/path bash docker/scripts/generate-vault-secrets.sh
#
# The generated vault.yml is read by deploy.sh to populate docker/.env and
# docker/redis/acl.conf.  Never commit vault.yml to source control.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCKER_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
VAULT_FILE="${VAULT_DIR:-${DOCKER_DIR}}/vault.yml"

_pass() { openssl rand -base64 $(( ${1:-16} * 3 / 4 + 1 )) | tr -d "=+/\n" | cut -c1-${1:-16}; }
_hex()  { openssl rand -hex ${1:-16}; }

echo "🔧 Generating Docker deployment secrets..."

# ---------------------------------------------------------------------------
# PostgreSQL — single shared instance (admin + per-service users)
# -------------------------------------------------------------------------
POSTGRES_ADMIN_PASSWORD="$(_pass 20)"        # postgres superuser (healthchecks / ops)
LITELLM_DB_PASSWORD="$(_pass 20)"
FLOWISE_DB_PASSWORD="$(_pass 20)"
LANGFUSE_DB_PASSWORD="$(_pass 20)"
PGVECTOR_PASSWORD="$(_pass 20)"               # agentuser on agentdb (vector store)

# -------------------------------------------------------------------------
# Core — LiteLLM GenAI Gateway
# -------------------------------------------------------------------------
LITELLM_MASTER_KEY="sk-$(_hex 10)"
LITELLM_SALT_KEY="$(_hex 10)"
POSTGRESQL_PASSWORD="${LITELLM_DB_PASSWORD}"   # k8s compat alias (same value)

# ---------------------------------------------------------------------------
# Redis — admin password + per-service ACL credentials
# ---------------------------------------------------------------------------
REDIS_PASSWORD="$(_pass 20)"           # admin user (health checks / ops)
LITELLM_REDIS_PASSWORD="$(_pass 20)"
FLOWISE_REDIS_PASSWORD="$(_pass 20)"
LANGFUSE_REDIS_PASSWORD="$(_pass 20)"

# ---------------------------------------------------------------------------
# Flowise — Agent Builder
# ---------------------------------------------------------------------------
# No admin credentials are generated here on purpose.  Flowise 3.1.2 has no
# environment-based admin bootstrap (the image contains no reference to
# FLOWISE_ADMIN_EMAIL / FLOWISE_ADMIN_PASSWORD, and its `user` CLI can only reset
# the password of an existing account).  The owner is created by an administrator
# through the UI's "Setup Account" page on first run, over a loopback-bound port.
# Generating credentials that nothing consumes would imply a pre-provisioned admin
# that does not exist.  See docker/README.md.
AGENTICAI_POSTGRES_PASSWORD="${FLOWISE_DB_PASSWORD}"  # k8s compat alias (same value)

# ---------------------------------------------------------------------------
# Consumer Portal
# ---------------------------------------------------------------------------
NEXTAUTH_SECRET="$(_hex 16)"

# ---------------------------------------------------------------------------
# Langfuse LLM Tracing
# ---------------------------------------------------------------------------
LANGFUSE_SECRET_KEY="lf_sk_$(_hex 10)"
LANGFUSE_PUBLIC_KEY="lf_pk_$(_hex 10)"
LANGFUSE_NEXTAUTH_SECRET="$(_hex 16)"
LANGFUSE_INIT_USER_PASSWORD="$(_pass 20)"

# ---------------------------------------------------------------------------
# ClickHouse / MinIO
# ---------------------------------------------------------------------------
CLICKHOUSE_PASSWORD="$(_pass 20)"
MINIO_USER="minio"
MINIO_SECRET="$(_pass 20)"

# ---------------------------------------------------------------------------
# Write vault.yml
# ---------------------------------------------------------------------------
mkdir -p "$(dirname "${VAULT_FILE}")"
cat > "${VAULT_FILE}" << EOF
# =============================================================================
# Docker Vault — Auto-generated by generate-vault-secrets.sh
# Generated: $(date)
#
# DO NOT commit this file to source control.
# Re-run generate-vault-secrets.sh to rotate all credentials (requires restart).
# =============================================================================

# ---------------------------------------------------------------------------
# LiteLLM — GenAI Gateway
# ---------------------------------------------------------------------------
litellm_master_key: "${LITELLM_MASTER_KEY}"
litellm_salt_key: "${LITELLM_SALT_KEY}"
# PostgreSQL — single shared instance
# postgres superuser (health checks / init operations)
postgres_admin_password: "${POSTGRES_ADMIN_PASSWORD}"

# Per-service database users
litellm_db_password: "${LITELLM_DB_PASSWORD}"
flowise_db_password: "${FLOWISE_DB_PASSWORD}"
langfuse_db_password: "${LANGFUSE_DB_PASSWORD}"
pgvector_password: "${PGVECTOR_PASSWORD}"

# k8s compatibility aliases (same values)
postgresql_password: "${POSTGRESQL_PASSWORD}"
agenticai_postgres_password: "${AGENTICAI_POSTGRES_PASSWORD}"

# ---------------------------------------------------------------------------
# Redis — admin + per-service ACL passwords
# admin:         health checks and operational access
# litellm:       routing cache
# flowise:       BullMQ job queue
# langfuse:      event/trace queue
# ---------------------------------------------------------------------------
redis_password: "${REDIS_PASSWORD}"
litellm_redis_password: "${LITELLM_REDIS_PASSWORD}"
flowise_redis_password: "${FLOWISE_REDIS_PASSWORD}"
langfuse_redis_password: "${LANGFUSE_REDIS_PASSWORD}"

# ---------------------------------------------------------------------------
# Flowise — Agent Builder
# ---------------------------------------------------------------------------
# Owner account is created interactively on first run — see note above.

# ---------------------------------------------------------------------------
# Consumer Portal
# ---------------------------------------------------------------------------
nextauth_secret: "${NEXTAUTH_SECRET}"

# ---------------------------------------------------------------------------
# Langfuse LLM Tracing  (profile: observability)
# ---------------------------------------------------------------------------
langfuse_secret_key: "${LANGFUSE_SECRET_KEY}"
langfuse_public_key: "${LANGFUSE_PUBLIC_KEY}"
langfuse_nextauth_secret: "${LANGFUSE_NEXTAUTH_SECRET}"
langfuse_init_user_password: "${LANGFUSE_INIT_USER_PASSWORD}"

# ---------------------------------------------------------------------------
# ClickHouse / MinIO  (profile: observability)
# ---------------------------------------------------------------------------
clickhouse_password: "${CLICKHOUSE_PASSWORD}"
minio_user: "${MINIO_USER}"
minio_secret: "${MINIO_SECRET}"
EOF

chmod 600 "${VAULT_FILE}"
echo "✔  Secrets written to ${VAULT_FILE}"
echo ""
echo "  Next: edit docker/config.cfg, then run:"
echo "    bash docker/deploy.sh"
